"""Unit tests for migrate.py: moving downloads from earlier folder layouts (no QGIS needed)."""

import os

from lidar_downloader_uk import api, migrate, storage


def touch(path, data=b'x'):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'wb') as f:
        f.write(data)


VRT = '''<VRTDataset rasterXSize="10" rasterYSize="10">
  <VRTRasterBand dataType="Float32" band="1">
    <SimpleSource>
      <SourceFilename relativeToVRT="{rel}">{path}</SourceFilename>
    </SimpleSource>
  </VRTRasterBand>
</VRTDataset>
'''


def legacy_layout(root):
    """Mimics a real download folder from v0.4/v0.5."""
    j = os.path.join
    # Composite DTM 2022 1m in the old main-folder layout: one kept zip, one zip deleted
    touch(j(root, 'extracted', 'TQ74NE', 'TQ74ne_DTM_1m.tif'))
    touch(j(root, 'extracted', 'TQ76NW', 'TQ76nw_DTM_1m.tif'))
    touch(j(root, 'TQ74NE.zip'))
    # VRTs made by earlier versions (relative, and absolute)
    touch(j(root, 'extracted', 'combined.vrt'), VRT.format(rel=1, path='TQ74NE/TQ74ne_DTM_1m.tif').encode())
    touch(j(root, 'medway_combined.vrt'), VRT.format(rel=1, path='extracted/TQ76NW/TQ76nw_DTM_1m.tif').encode())
    touch(j(root, 'absolute.vrt'), VRT.format(rel=0, path=j(root, 'extracted', 'TQ74NE', 'TQ74ne_DTM_1m.tif')).encode())
    # Absolute path with mixed separators, as QGIS on Windows writes them (e.g. S:/LiDAR Data\extracted\...)
    mixed = root.replace(os.sep, '/') + os.sep + os.sep.join(['extracted', 'TQ76NW', 'TQ76nw_DTM_1m.tif'])
    touch(j(root, 'extracted', 'mixed.vrt'), VRT.format(rel=0, path=mixed).encode())
    # v0.5 dataset folders
    touch(j(root, 'vertical_aerial_photography_tiles_rgbn_2009_0.2m', 'extracted', 'SU12NE', 'Ortho_RGBN_1.ecw'))
    obl = j(root, 'oblique_aerial_photography_tiles_incident_response_latest', 'extracted', 'SU12NE')
    touch(j(obl, 'Obliques_S23_016_20230121_141845.jpg'))
    touch(j(obl, 'photo_locations.gpkg'))            # generated by the plugin, holds old paths
    obl2 = j(root, 'oblique_aerial_photography_tiles_incident_response_latest', 'extracted', 'TQ84SW')
    touch(j(obl2, 'Obliques_S20_060_200217_102520.jpg'))  # 6-digit date: 17 Feb 2020
    touch(j(root, 'national_lidar_programme_dtm_latest_1m', 'extracted', 'SU12NW', 'SU12nw_DTM.tif'))  # year unknown
    touch(j(root, 'lidar_point_cloud_2012', 'extracted', 'SU12NE', 'a.laz'))
    touch(j(root, 'notes', 'readme.txt'))            # unrelated folder, left alone


def test_plan(tmp_path):
    root = str(tmp_path)
    legacy_layout(root)
    moves, skipped = migrate.plan(root)
    counts = migrate.summary(moves)
    assert counts == {
        api.DEFAULT_DATASET: 2,
        api.Dataset('vertical_aerial_photography_tiles_rgbn', '2009', '0.2'): 1,
        api.Dataset('oblique_aerial_photography_tiles_incident_response', '2023', 'NaN'): 1,
        api.Dataset('oblique_aerial_photography_tiles_incident_response', '2020', 'NaN'): 1,
        api.Dataset('lidar_point_cloud', '2012', 'NaN'): 1,
    }
    assert len(moves) == 7  # 6 tile folders + 1 zip
    assert [os.path.basename(p) for p, _ in skipped] == ['SU12NW']
    assert 'survey year unknown' in skipped[0][1]


def test_apply_moves_tiles_and_rewrites_vrts(tmp_path):
    root = str(tmp_path)
    legacy_layout(root)
    moves, _ = migrate.plan(root)
    done, errors = migrate.apply(root, moves)
    assert errors == [] and len(done) == len(moves)

    dtm = os.path.join(root, 'lidar_composite_dtm', '1m', '2022')
    assert storage.scan_downloaded_tiles(dtm) == ['TQ74NE', 'TQ76NW']
    assert os.path.exists(os.path.join(dtm, 'TQ74NE.zip'))
    rgbn = os.path.join(root, 'vertical_aerial_photography_tiles_rgbn', '0.2m', '2009')
    assert storage.find_raster_files(rgbn, 'SU12NE')
    obl = os.path.join(root, 'oblique_aerial_photography_tiles_incident_response', '2023', 'SU12NE')
    assert os.path.exists(os.path.join(obl, 'Obliques_S23_016_20230121_141845.jpg'))
    assert not os.path.exists(os.path.join(obl, 'photo_locations.gpkg'))  # stale, rebuilt on next load
    assert storage.find_point_cloud_files(os.path.join(root, 'lidar_point_cloud', '2012'), 'SU12NE')
    # Emptied old folders are tidied; ones still holding something (a VRT, an unknown-year tile) stay
    assert not os.path.exists(os.path.join(root, 'lidar_point_cloud_2012'))
    assert os.path.exists(os.path.join(root, 'extracted', 'combined.vrt'))
    assert os.path.exists(os.path.join(root, 'national_lidar_programme_dtm_latest_1m', 'extracted', 'SU12NW'))
    assert os.path.exists(os.path.join(root, 'notes', 'readme.txt'))

    changed = migrate.rewrite_vrts(root, done)
    names = sorted(os.path.basename(p) for p in changed)
    assert names == ['absolute.vrt', 'combined.vrt', 'medway_combined.vrt', 'mixed.vrt']
    mixed = open(os.path.join(root, 'extracted', 'mixed.vrt'), encoding='utf-8').read()
    assert os.path.join(dtm, 'TQ76NW', 'TQ76nw_DTM_1m.tif') in mixed
    medway = open(os.path.join(root, 'medway_combined.vrt'), encoding='utf-8').read()
    assert '>lidar_composite_dtm/1m/2022/TQ76NW/TQ76nw_DTM_1m.tif<' in medway
    combined = open(os.path.join(root, 'extracted', 'combined.vrt'), encoding='utf-8').read()
    assert '>../lidar_composite_dtm/1m/2022/TQ74NE/TQ74ne_DTM_1m.tif<' in combined
    absolute = open(os.path.join(root, 'absolute.vrt'), encoding='utf-8').read()
    assert os.path.join(dtm, 'TQ74NE', 'TQ74ne_DTM_1m.tif') in absolute
    assert migrate.rewrite_vrts(root, done) == []  # idempotent


def test_new_path_and_nothing_to_do(tmp_path):
    root = str(tmp_path)
    legacy_layout(root)
    moves, _ = migrate.plan(root)
    old = os.path.join(root, 'extracted', 'TQ74NE', 'TQ74ne_DTM_1m.tif')
    assert migrate.new_path(old, moves) == os.path.join(root, 'lidar_composite_dtm', '1m', '2022', 'TQ74NE',
                                                        'TQ74ne_DTM_1m.tif')
    assert migrate.new_path(os.path.join(root, 'notes', 'readme.txt'), moves) is None
    migrate.apply(root, moves)
    moves_again, skipped_again = migrate.plan(root)
    assert moves_again == [] and len(skipped_again) == 1  # only the unknown-year tile remains


def test_existing_destination_is_never_overwritten(tmp_path):
    root = str(tmp_path)
    touch(os.path.join(root, 'extracted', 'TQ74NE', 'old.tif'))
    touch(os.path.join(root, 'lidar_composite_dtm', '1m', '2022', 'TQ74NE', 'new.tif'))
    moves, skipped = migrate.plan(root)
    assert moves == [] and 'already exists' in skipped[0][1]


def test_empty_or_missing_folder(tmp_path):
    assert migrate.plan(str(tmp_path)) == ([], [])
    assert migrate.plan(str(tmp_path / 'missing')) == ([], [])


def test_failed_move_changes_nothing(tmp_path, monkeypatch):
    """A move that fails (e.g. a file open in QGIS on Windows) must not leave a partial copy."""
    root = str(tmp_path)
    legacy_layout(root)
    moves, _ = migrate.plan(root)

    def refuse(src, dst):
        raise PermissionError(5, 'Access is denied')
    monkeypatch.setattr(migrate.os, 'rename', refuse)
    done, errors = migrate.apply(root, moves)
    assert done == [] and len(errors) == len(moves)
    assert os.path.exists(os.path.join(root, 'extracted', 'TQ74NE', 'TQ74ne_DTM_1m.tif'))
    assert not os.path.exists(os.path.join(root, 'lidar_composite_dtm', '1m', '2022', 'TQ74NE'))
